name = 'Letterbox'
license = 'MIT'
licenselink = 'https://github.com/lubeso/hugo-theme-letterbox/LICENSE'
description = 'Theme for the Letterbox website.'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/lubeso/hugo-theme-letterbox'

[author]
  name = 'Luis Becerra Solis'
  homepage = 'https://www.lubeso.dev'
